name: build/deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:bookworm
    steps:
      - name: install aux deps
        run: apt update && apt -y --no-install-recommends install git ca-certificates curl gpg

      - name: add pgdg pkg repo
        run: >
          echo "deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" >> /etc/apt/sources.list.d/pgdg.list &&
          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg

      - run: apt update

      - name: clone repo
        uses: actions/checkout@v3

      - name: install build deps
        run: apt -y --no-install-recommends build-dep .

      - name: build package
        run: dpkg-buildpackage -us -uc -b

      - uses: actions/upload-artifact@v3
        with:
          name: pkg
          path: ../*.deb
          retention-days: 1

  deploy:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    container: debian:bookworm
    steps:
      - name: install curl
        run: apt update && apt -y --no-install-recommends install curl

      - uses: actions/download-artifact@v3
        with:
          name: pkg

      - name: upload pkg to the bookworm 1.13
        run: ci/deploy.sh bookworm 1.13 main *.deb
        env:
          PKG_API_BASE: ${{secrets.PKG_API_BASE}}
